### PR TITLE
Add feature for user to set card margins

### PR DESCRIPTION
**Pull request by patuoynageek**

### CODE REVIEW

**Comment by ketanchoyal** [comment]
@patuoynageek thanks but  I cannot merge this PR since you only added margin in the radio button, add it to the group button as well then I'll merge it

**Comment by patuoynageek** [comment]
sorry, can you please clarify where/what you are referring to?

**Comment by ketanchoyal** [comment]
can you add the same thing for grouped button as well

**Comment by patuoynageek** [comment]
Changes has been added to both classes

**Pull request merged**
