### PR TITLE
Adding some customization

### PR DESCRIPTION
**Pull request by pishguy**
in this update we will have supported some features such as `border width` and `multiple line in button texts`

### CODE REVIEW

**Comment by ketanchoyal** [comment]
@MahdiPishguy sorry for the trouble but What I meant was that you have to make the PR in dev branch not in master branch. I have to test it in dev branch then I'll merge it to master. Master branch has auto publishing action so as soon as we push something it'll publish it without testing.

**Comment by pishguy** [comment]
@ketanchoyal ok. i get permission error now

remote: Permission to ketanchoyal/custom_radio_grouped_button.git denied to pishguy.

**Comment by ketanchoyal** [comment]
no worries, I opened it thanks

**Comment by pishguy** [comment]
@ketanchoyal i get this error again

```
Username for 'https://github.com': pishguy
Password for 'https://pishguy@github.com':
remote: Permission to ketanchoyal/custom_radio_grouped_button.git denied to pishguy.
fatal: unable to access 'https://github.com/ketanchoyal/custom_radio_grouped_button.git/': The requested URL returned error: 403
```

**Pull request closed without merging**
